# Generated by Django 5.1.5 on 2025-03-06 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id_complex', models.AutoField(primary_key=True, serialize=False)),
                ('full_complex_name', models.TextField()),
                ('short_complex_name', models.TextField(blank=True, null=True)),
                ('area_complex_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address_complex', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id_division', models.AutoField(primary_key=True, serialize=False)),
                ('name_division', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('name_region', models.CharField(max_length=100)),
                ('code_region', models.CharField(blank=True, max_length=50, null=True)),
                ('area_region_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('population', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('building_density', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('urbanization_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id_object', models.AutoField(primary_key=True, serialize=False)),
                ('id_ip', models.IntegerField()),
                ('code_by_classifier', models.CharField(max_length=14)),
                ('full_object_name', models.TextField()),
                ('short_object_name', models.TextField(blank=True, null=True)),
                ('visibility_level', models.IntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4')], null=True)),
                ('security_classification', models.IntegerField(blank=True, choices=[(1, 'Class 1'), (2, 'Class 2'), (3, 'Class 3'), (4, 'Class 4')], null=True)),
                ('address_object', models.TextField(blank=True, null=True)),
                ('area_object_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.complex')),
                ('id_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.division')),
                ('id_main_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.object')),
                ('id_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region')),
            ],
            options={
                'db_table': 'Object',
            },
        ),
    ]
