# Generated by Django 5.1.5 on 2025-03-06 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_complex_division_region_object'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='object',
            table='object',
        ),
    ]
