# Generated by Django 5.1.5 on 2025-03-06 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_object_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='object',
            table=None,
        ),
    ]
