# Generated by Django 5.1.5 on 2025-03-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_object_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BudgetingType',
            fields=[
                ('id_budgeting_type', models.AutoField(primary_key=True, serialize=False)),
                ('name_budgeting_type', models.TextField()),
            ],
            options={
                'db_table': 'budgeting_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryIndicators',
            fields=[
                ('id_category', models.AutoField(primary_key=True, serialize=False)),
                ('name_category', models.TextField()),
            ],
            options={
                'db_table': 'category_indicators',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CostIndicatorsMonthlyVat',
            fields=[
                ('id_indicator', models.AutoField(primary_key=True, serialize=False)),
                ('price_level', models.CharField(blank=True, max_length=10, null=True)),
                ('construction_works', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('equipment', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('design_works', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('other', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('miscellaneous', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('fact_or_plan', models.CharField(blank=True, max_length=10, null=True)),
                ('cumulative_effect', models.BooleanField()),
            ],
            options={
                'db_table': 'cost_indicators_monthly_vat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id_country', models.AutoField(primary_key=True, serialize=False)),
                ('name_country', models.CharField(max_length=70)),
                ('code_country', models.CharField(blank=True, max_length=10, null=True)),
                ('capital', models.CharField(blank=True, max_length=70, null=True)),
                ('continent', models.CharField(blank=True, max_length=20, null=True)),
                ('official_language', models.TextField(blank=True, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuratorIp',
            fields=[
                ('id_curator', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'curator_ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerIp',
            fields=[
                ('id_customer', models.AutoField(primary_key=True, serialize=False)),
                ('participation_start_date', models.DateField()),
                ('participation_end_date', models.DateField()),
            ],
            options={
                'db_table': 'customer_ip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.TextField()),
                ('creation_date', models.DateField()),
                ('last_modified', models.DateTimeField()),
                ('document_type', models.CharField(blank=True, max_length=20, null=True)),
                ('link', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseDirection',
            fields=[
                ('id_expense_direction', models.AutoField(primary_key=True, serialize=False)),
                ('name_expense_direction', models.TextField()),
            ],
            options={
                'db_table': 'expense_direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id_individual', models.AutoField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'individual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvestmentProject',
            fields=[
                ('id_ip', models.AutoField(primary_key=True, serialize=False)),
                ('full_ip_name', models.TextField()),
                ('short_ip_name', models.TextField(blank=True, null=True)),
                ('goal_ip', models.TextField(blank=True, null=True)),
                ('code_ip', models.CharField(blank=True, max_length=40, null=True)),
                ('start_date_ip', models.IntegerField(blank=True, null=True)),
                ('end_date_ip', models.IntegerField(blank=True, null=True)),
                ('decision_level', models.TextField(blank=True, null=True)),
                ('significance_flag', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'investment_project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyEvents',
            fields=[
                ('id_key_event', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.TextField()),
                ('work_number', models.TextField(blank=True, null=True)),
                ('start_event_date', models.DateField()),
                ('end_event_date', models.DateField()),
                ('event_type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'key_events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainComplex',
            fields=[
                ('id_complex', models.AutoField(primary_key=True, serialize=False)),
                ('full_complex_name', models.TextField()),
                ('short_complex_name', models.TextField(blank=True, null=True)),
                ('area_complex_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address_complex', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_complex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainDivision',
            fields=[
                ('id_division', models.AutoField(primary_key=True, serialize=False)),
                ('name_division', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'main_division',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainMymodel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'main_mymodel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainRegion',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('name_region', models.CharField(max_length=100)),
                ('code_region', models.CharField(blank=True, max_length=50, null=True)),
                ('area_region_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('population', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('building_density', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('urbanization_level', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'main_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectProgram',
            fields=[
                ('id_object_program', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'object_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectStep',
            fields=[
                ('id_object_step', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'object_step',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id_organization', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('short_name', models.TextField(blank=True, null=True)),
                ('okved', models.CharField(blank=True, max_length=20, null=True)),
                ('okpo', models.CharField(blank=True, max_length=20, null=True)),
                ('duns', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('website', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id_phase', models.AutoField(primary_key=True, serialize=False)),
                ('phase_number', models.IntegerField()),
                ('full_phase_name', models.TextField()),
                ('short_phase_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id_program', models.AutoField(primary_key=True, serialize=False)),
                ('full_program_name', models.TextField()),
                ('short_program_name', models.TextField(blank=True, null=True)),
                ('description_program', models.TextField(blank=True, null=True)),
                ('document_program', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectKvl',
            fields=[
                ('id_pr_kvl', models.AutoField(primary_key=True, serialize=False)),
                ('name_pr_kvl', models.TextField()),
                ('goal_pr_kvl', models.TextField(blank=True, null=True)),
                ('capital_investment_character', models.TextField(blank=True, null=True)),
                ('technical_specification_approved', models.BooleanField()),
                ('docs_approved', models.BooleanField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('fact_or_plan', models.CharField(blank=True, max_length=10, null=True)),
                ('cumulative_effect', models.BooleanField()),
            ],
            options={
                'db_table': 'project_kvl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id_stage', models.AutoField(primary_key=True, serialize=False)),
                ('stage_number', models.IntegerField()),
                ('full_stage_name', models.TextField()),
                ('short_stage_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id_step', models.AutoField(primary_key=True, serialize=False)),
                ('step_number', models.IntegerField()),
                ('full_step_name', models.TextField()),
                ('short_step_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'step',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TechCustomer',
            fields=[
                ('id_tech_customer', models.AutoField(primary_key=True, serialize=False)),
                ('participation_start_date', models.DateField()),
                ('participation_end_date', models.DateField()),
            ],
            options={
                'db_table': 'tech_customer',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='complex',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
