# Generated by Django 5.1.5 on 2025-03-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='complex',
            table='complex',
        ),
        migrations.AlterModelTable(
            name='division',
            table='division',
        ),
        migrations.AlterModelTable(
            name='object',
            table='object',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
    ]
